name: GitHub Actions Demo
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Set Start Time
        id: start-time
        run: |
          echo "::set-output name=time::$(TZ='Europe/Paris' date +'%H:%M:%S')"

      - name: Install dependencies
        run: npm install

      - name: Use Start Time in Subsequent Steps
        run: |
          start_time="${{ steps.start-time.outputs.time }}"

      - name: Install dependencies
        run: npm install
